[package]
name = "simplineage-importers"
description = "Metadata importers and plugin interface for SimpLineage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
simplineage-core.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
